/*
 * I used some emoji images from: https://sensa.co/emoji
 * 
 * Use this command to resize the . PNG files:
 * ..\mogrify.exe -resize 220x220 *.png
 */
const char *fn[] = {"Angry face.png",
    "Anguished face.png",
    "Anxious face with sweat.png",
    "Astonished face.png",
    "Beaming face with smiling eyes.png",
    "Cold face.png",
    "Confounded face.png",
    "Cowboy hat face.png",
    "Crying face.png",
    "Dissapointed face.png",
    "Dizzy face.png",
    "Downcast face with sweat.png",
    "Drooling face.png",
    "Expressioless face.png",
    "Face blowing a kiss.png",
    "Face savoring food.png",
    "Face screaming in fear.png",
    "Face with hand over mouth.png",
    "Face with head-bandage.png",
    "Face with medical mask.png",
    "Face with monocle.png",
    "Face with open mouth.png",
    "Face with raised eyebrow.png",
    "Face with rolling eyes.png",
    "Face with steam from nose.png",
    "Face with symbols on mouth.png",
    "Face with tears of joy.png",
    "Face with thermometer.png",
    "Face with tongue.png",
    "Face without mouth.png",
    "Fearful face.png",
    "Flushed face.png",
    "Frowning face with open mouth.png",
    "Frowning face.png",
    "Grimacing face.png",
    "Grinning face with big eyes.png",
    "Grinning face with sweat.png",
    "Grinning face-1.png",
    "Grinning face.png",
    "Grinning squinting face.png",
    "Hot face.png",
    "Hugging face.png",
    "Hushed face.png",
    "Kissing face with closed eyes.png",
    "Kissing face with smiling eyes.png",
    "Kissing face.png",
    "Loudly crying face.png",
    "Lying face.png",
    "Money mouth face.png",
    "Nauseated face.png",
    "Nerd face.png",
    "Neutral face.png",
    "Partying face.png",
    "Pensive face.png",
    "Pleading face.png",
    "Pouting face.png",
    "Relieved face.png",
    "Sad but relieved face.png",
    "Scrunched face.png",
    "Shushing face.png",
    "Sleep face.png",
    "Sleepy face.png",
    "Slightly frowning face.png",
    "Slightly smiling face.png",
    "Smiling face with halo.png",
    "Smiling face with heart-eyes.png",
    "Smiling face with hearts.png",
    "Smiling face with smiling eyes.png",
    "Smiling face with sunglasses.png",
    "Smiling face.png",
    "Smirking face.png",
    "Sneezing face.png",
    "Squinting face with tongue.png",
    "Thinking face.png",
    "Tired face.png",
    "Unamused face.png",
    "Upside-down face.png",
    "Vomiting face.png",
    "Weary face.png",
    "Winking face with tongue.png",
    "Winking face.png",
    "Woozy face.png",
    "Worried face-1.png",
    "Worried face.png",
    "Yawning face.png",
    "Zany face.png",
    "Zipper-mouth face.png"};
    
